name: testing workflow
on:
  pull_request:
    branches:
      - testing

jobs:
  testing-trigger:
    name: testing trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo
        run: pws